### ISSUE TITLE
README is mentioning appengine-web.xml, but this file does not exist in the repository

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/appengine-java-vm-hello#6]
Providing only the README, It is not clear to me what or where is appengine-web.xml.

**Comment by erugeri** [comment]
You can find it there: https://github.com/GoogleCloudPlatform/appengine-java-vm-hello/blob/master/src/main/webapp/WEB-INF/appengine-web.xml

**Comment by steren** [comment]
Thanks. What do you think of adding this as a precision in the README?

**Comment by ludoch** [comment]
it is there https://github.com/GoogleCloudPlatform/appengine-java-vm-hello/blob/master/src/main/webapp/WEB-INF/appengine-web.xml
