### ISSUE TITLE
Uncovered methods warning on startup

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/appengine-java-vm-hello#9]
Using the guestbook example webapp, the jetty log shows that the webapp has some security constraint mappings that leave some http methods uncovered. Note that this log message is a new requirement from the Servlet 3.0 spec.

2015-08-06 06:19:47.652:WARN:oejs.SecurityHandler:main: ServletContext@c.g.a.v.j.VmRuntimeWebAppContext@624733f0{/,file:/var/lib/jetty/webapps/root/,STARTING}{/root} has uncovered http methods for path: /

**Comment by ludoch** [comment]
Easy fix?

**Comment by janbartel** [comment]
@ludoch 

Yes, it should be the same fix as discussed in this pull request: https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/36

**Comment by ludoch** [comment]
Thanks!
Fixed
